### ISSUE TITLE
isBN breaks in production

### ISSUE THREAD

**Issue by epiqueras** [ethereum/web3.js#1777]
Minifying the code makes the BN instance's `constructor.name !== 'BN'` so it breaks web3's implementation of `isBN`.

**Comment by nivida** [comment]
Hay @epiqueras I've tested it with the minified version of web3 and cant reproduce your case.

Tested with:
``` 
var BN = web3.utils.BN;
var bigNumber = new BN(1234);
console.log(web3.utils.isBN(bigNumber));
```

The result I got: 
```true```

**Comment by loliconer** [comment]
@nivida 
There is no problem when using web3.min.js. But error occurs when using webpack to minify code.
```
import Web3 from 'web3

console.log(Web3.utils.isBN(Web3.utils.toBN(100000000))) // false, because the constructor.name becomes 'o', so 'o' !== 'BN'
console.log(Web3.utils.isBN(new Web3.utils.BN(100000000))) // true
```

**Comment by nivida** [comment]
I think it should be solved with the PR #2000

**Comment by such** [comment]
@nivida what makes you think that? I have just looked at the code and `isBN` still uses `constructor.name` that causes the issue here. But I'm not a minification expert! Is there anything I'm missing?

**Comment by rhlsthrm** [comment]
Ran into this issue in a `create-react-app` implementation. Googling around I found this: https://github.com/indutny/bn.js/issues/133.

Web3 should use the isBN function from the BN.js library directly.

**Comment by chapati23** [comment]
This is still a problem. Bumping the version of `bn.js` to `4.11.8` fixed it for me, temporary fix is possible via yarn resolutions, just add the following to your `package.json`:

```json
  "resolutions": {
    "bn.js": "4.11.8"
  }
```
