### ISSUE TITLE
pathological npm install behavior re: web3-providers-ws

### ISSUE THREAD

**Issue by michaelsbradleyjr** [ethereum/web3.js#1914]
I'm experiencing "weird things" related to:

https://github.com/ethereum/web3.js/blob/v1.0.0-beta.35/packages/web3-providers-ws/package.json#L12

In a project that specifies `"web3": "1.0.0-beta.35"` in its package.json, with a fresh install (`rm -rf node_modules && npm i .`) there's some package-lock churn and then `npm ls | less` reveals this:

```
│ │ │ └─┬ web3-providers-ws@1.0.0-beta.35
│ │ │   ├── underscore@1.8.3
│ │ │   ├── web3-core-helpers@1.0.0-beta.35 deduped
│ │ │   └─┬ websocket@1.0.26 invalid (git://github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2)
│ │ │     ├── debug@2.6.9 extraneous
│ │ │     ├── nan@2.11.0 deduped
│ │ │     ├── UNMET DEPENDENCY typedarray-to-buffer@^3.1.2
│ │ │     └── UNMET DEPENDENCY yaeti@^0.0.6
```

`typedarray-to-buffer` is, after install, definitely missing, and sometimes `websocket` is missing as well. In other words, the installation is broken.

I can "fix" it by doing: `npm un web3 && npm i --save-exact web3@1.0.0-beta.35`. There's more package-lock churn and the missing deps are no longer missing. But then with a fresh install (e.g. on travis or appveyor), I'm back where I started.

node: `8.11.4`
npm: `6.4.1`
platforms affected: macOS, Linux, Windows.

**Comment by daffl** [comment]
This should be fixed via #1907 but has not been released yet.

**Comment by michaelsbradleyjr** [comment]
@daffl good to hear. Any ETA on the next version?

Also, when it does land, perhaps it would be good to [deprecate](https://docs.npmjs.com/cli/deprecate) all affected versions of web3 — beta.35, beta.36, others?

**Comment by evbots** [comment]
@michaelsbradleyjr 

I have a vanilla install of create-react-app, and tried adding a specific reference to `"web3": "1.0.0-beta.35"` in dependencies. When i generate a `package-lock.json` via `npm install` under npm versions 5.10.0, 6.2.0, 6.4.1, i get the following error in my build:
```
Module not found: Error: Can't resolve 'websocket' in '/home/circleci/dex_terminal_evan/node_modules/web3-providers-ws/src'
```
Alternatively, generating a `package-lock.json` under npm version 5.6.0, the build passes. It also builds fine when I run install without a `package-lock.json`.

I'm not sure what the connection is between this and #1907, @daffl can you elaborate?

**Comment by nivida** [comment]
This should be solved in the next build.

**Comment by birdofpreyru** [comment]
Any chance you release the fixed version any soon?  Having a simple fix for an annoying bug, and not releasing it for two months, doesn't look like a good dev practice, even if we talk about a beta version.

**Comment by nivida** [comment]
@birdofpreyru Yeah I know it should be released next month. Sorry for the long outstanding release but I have to clean up a lot of things before I can really maintain/fixing this lib.

**Comment by darioAnongba** [comment]
thanks for the update @nivida ! Keep the good work. Bug still present in beta.37

**Comment by leonprou** [comment]
For me it works fine on Mac, but it's failing on our build machines (Linux).
This is started like a week ago

**Comment by kolya182** [comment]
@leonprou Same for me, failing on Heroku and works on Mac. Did you managed to fix it ?

**Comment by leonprou** [comment]
@kolya182 yeah, I added the missing dependency to my `package.json` as a temporary solution. for me it was `websocket` package.

**Comment by kolya182** [comment]
@leonprou Thanks
Temp fix for me `npm i --save websocket`

"node": `10.15.0`,
"npm": `6.4.1`

**Comment by Richard-RichIntellect** [comment]
I just ran npm install and it worked for me.

**Comment by nivida** [comment]
Should be fixed with the PR #2000. 
Feel free to test it with the git tag: https://github.com/ethereum/web3.js/tree/v1.0.0-beta.38-rc2
