### ISSUE TITLE
connection not open on send() 

### ISSUE THREAD

**Issue by deacix** [ethereum/web3.js#3064]
Hi everyone!
I get this error message:

connection not open on send() 

with version: 1.2.1

After long running of my dApp on https://1inch.exchange

**Comment by nivida** [comment]
Thanks for opening this issue! We fixed this during the refactoring of the whole code base but had to split it up as 1.x and 2.x which means this fix didn’t get applied to the current 1.0 version. We are currently plan to back-port all fixed bugs from the refactoring we have done. I apologize for the current situation you are in.

**Comment by deacix** [comment]
> Thanks for opening this issue! We fixed this during the refactoring of the whole code base but had to split it up as 1.x and 2.x which means this fix didn’t get applied to the current 1.0 version. We are currently plan to back-port all fixed bugs from the refactoring we have done. I apologize for the current situation you are in.

Hey! Thanks for fast answer! 
Can you give me a link to the lines of code which fix it in 2.x? How i said i am not using 1.0. I am using 1.2.1!

**Comment by avoloshko** [comment]
Can someone still provide a reference the the fix?

**Comment by deacix** [comment]
> Can someone still provide a reference the the fix?

I just migrated our https://1inch.exchange to the latest 2.x version.. Is working fine in an Angular dApp after a small fix in the script package..

**Comment by sirpy** [comment]
@deacix this still happens on 2.0.0 alpha using websockets
after the app is running for a while in background you go back to it
