### ISSUE TITLE
Unable to resolve module `crypto` from bignumber.js

### ISSUE THREAD

**Issue by mattvick** [ethereum/web3.js#576]
web3 `import` causes ``unable to resolve module `crypto` from /node_modules/bignumber.js/bignumber.js`` error.

Import code:

    import { default as Web3 } from 'web3';

web3 install command:

    $ npm install web3 --save

**Comment by mattvick** [comment]
I've resolved this by editing `line 2677` of the file `/node_modules/bignumber.js/bignumber.js` as follows:

    -if ( !crypto ) try { crypto = require('crypto'); } catch (e) {}
    +if ( !crypto ) try { crypto = require('crypto-js'); } catch (e) {}

So it would appear this appear this could be an issue with the `bignumber.js` dependency, or the way it's being imported. I'm unable to open issues on their [GitHub repo](https://github.com/debris/bignumber.js) so posting here.

**Comment by peculiarity** [comment]
Well crypto and crypto-js are different things. crypto is module which is part of Node and crypto-js is separate library.  If you check [node's crypto documentation](https://nodejs.org/api/crypto.html#crypto_crypto), you will find out that node might be configured in a way not to include crypto. Check how you built node.js or where you got it from.

**Comment by mattvick** [comment]
Thanks @peculiarity 

I've read the documentation link you've sent and believe I understand the situation now. However I still have the problem of not being able to find a node distribution that includes the crypto module.

I've tried installing node using all the following methods and I'm still seeing the error, after removing other versions, `rm -rf node_modules`, `watchman watch-del-all`, `rm -rf $TMPDIR/react-native-packager-*`, resetting Simulator, restarting etc, so I assume none of these builds include the crypto module. **How then should I build or find a build of node that includes the crypto module?**

    sudo port install nodejs6

    brew install node

    n stable

    https://nodejs.org/dist/v6.10.1/node-v6.10.1.pkg

**Comment by peculiarity** [comment]
Can you try to install the latest one 7.7.4 ? straight from their website?

**Comment by peculiarity** [comment]
Ok I have Windows 7  with node v6.2.2. Tried the example from the documentation in a local file and it finds the module. Can you try to create a separate simple file where you are invoking only the crypto module. See if it's found then it should be there and the problem might be indeed within web3.js impl.

**Comment by mattvick** [comment]
My current node installation is version `7.6.0` installed using `n stable`, which downloaded the distribution directly from the node website.

I've created a file `index.js` with the following content:

    var crypto = require('crypto');
    console.dir(crypto);

Running `$ node index.js` outputs details about the crypto object:

    { DEFAULT_ENCODING: 'buffer',
      constants:
       { SSL_OP_ALL: 2147486719,
         SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION: 262144,
         SSL_OP_CIPHER_SERVER_PREFERENCE: 4194304,
         SSL_OP_CISCO_ANYCONNECT: 32768,
         SSL_OP_COOKIE_EXCHANGE: 8192,
         SSL_OP_CRYPTOPRO_TLSEXT_BUG: 2147483648,
         SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS: 2048,
         SSL_OP_EPHEMERAL_RSA: 0,
         SSL_OP_LEGACY_SERVER_CONNECT: 4,
         SSL_OP_MICROSOFT_BIG_SSLV3_BUFFER: 32,
         SSL_OP_MICROSOFT_SESS_ID_BUG: 1,
         SSL_OP_MSIE_SSLV2_RSA_PADDING: 0,
         SSL_OP_NETSCAPE_CA_DN_BUG: 536870912,
         SSL_OP_NETSCAPE_CHALLENGE_BUG: 2,
         SSL_OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG: 1073741824,
        ...
      }
    }

**Comment by mattvick** [comment]
I believe the problem is because I'm using Ractive-Native, which does not copy built-in node packages over to the app.

I've found a related question on [StackExchange](http://stackoverflow.com/questions/39070103/what-is-the-simplest-way-to-include-a-node-package-that-requires-crypto-module-i). It's 7 months old but unfortunately with no answer :(

@peculiarity would you have any idea what is the simplest way to include a node package that requires crypto module in a React Native app?

**Comment by peculiarity** [comment]
Sorry mate , can't help you with this one. Never used  React nor React Native

**Comment by mattvick** [comment]
So the short answer about React-Native is that it's not possible to include built-in Node packages in the app.

Here's a Stack Overflow [question](http://stackoverflow.com/questions/42975157/how-do-i-include-and-require-a-built-in-node-package-in-a-react-native-app) with an [answer](http://stackoverflow.com/questions/42975157/how-do-i-include-and-require-a-built-in-node-package-in-a-react-native-app#answer-42975448) and a link to a React-Native [issue](https://github.com/facebook/react-native/issues/5049).

My questions to you `web3.js` guys are: 

- **How heavily does** `web3.js` **rely on on the built-in** `crypto` **Node package?**
- **Can we add an option to make** `web3.js` **work without relying on the built-in** `crypto` **Node package?** For example falling back to a `npm` Node package such as `crypto-js`.

**Comment by acroix** [comment]
@mattvick If you find a way to use ethereum on iOS and Android give me feedback. I am currently running web3j and using it as a NativeModule from Java in my application but can't really find something to make it work with iOS.

Thanks and keep this up to date ;)

**Comment by mattvick** [comment]
@acroix you can use [rn-nodeify](https://github.com/mvayngrib/rn-nodeify) or [ReactNativify](https://github.com/philikon/ReactNativify) to shim Node.js built in modules like Crypto. Then [web3.js](https://github.com/ethereum/web3.js/) or other similar JavaScript libraries, that depend on Crypto etc, will work.

**Comment by shayzluf** [comment]
@mattvick did you succeed in making web3.js run on react native that way? 
did you use the example transformer in ReactNativify?

**Comment by mattvick** [comment]
@shayzluf I'm not currently using web3.js but I am using the example transformer in ReactNativify to shim crypto and a couple of other built-ins

**Comment by davidperrenoud** [comment]
As the `resolutions` field  in package.json didn't seem to be working with my version of yarn, I replaced the following in `yarn.lock`:
```
"bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2":
  version "2.0.7"
  resolved "git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2"
```

With this:
```
bignumber.js@4.0.2, "bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2":
  version "4.0.2"
  resolved "https://registry.yarnpkg.com/bignumber.js/-/bignumber.js-4.0.2.tgz#2d1dc37ee5968867ecea90b6da4d16e68608d21d"
```

**Comment by corymsmith** [comment]
I was able to get this working using `rn-nodeify`, `react-native-crypto` and `react-native-randombytes` :)

**Comment by shkfnly** [comment]
@corymsmith can I ping you privately for more details?

**Comment by corymsmith** [comment]
@shkfnly You bet! I just sent you a connection request on LinkedIn

**Comment by corymsmith** [comment]
@shkfnly Are you still looking for more details?

**Comment by corymsmith** [comment]
I just push a working example app to: https://github.com/bullish-ventures/react-native-web3-example

**Comment by corymsmith** [comment]
Actually, I just tried using Web3 without doing any of the above and it now seems to work since the `bignumber` dependency was fixed.

**Comment by shayzluf** [comment]
@corymsmith Thank you for the update

**Comment by valashnez** [comment]
@corymsmith What version are you using that has the bignumber dependency fixed? I'm trying to build a react-native app as well and running into the same issue with web3 1.0.0-beta2.

**Comment by corymsmith** [comment]
@valashnez 0.19.0 but you may be able to use 0.20.0 as well

**Comment by luck2011** [comment]
I've got the exactly same issue with you but still cannot figure it out.
You are right, ```crypto``` is a built-in module in Node.js, I can't ```import``` it to React Native Apps. 😢

**Comment by davidperrenoud** [comment]
Here is a workaround to force version 4.0.2 of the official bignumber.js package using Yarn which seems to work fine:
https://github.com/ethereum/web3.js/issues/576#issuecomment-310031753

Why is the bignumber.js fork needed?

**Comment by flotwig** [comment]
If you're running into this issue while following the instructions from `ReactNativify` to inject `crypto` into the global scope, here's a quick fix.

Basically, the problem is that `bignumber.js` *used to* `require()` the crypto package, but the version used by web3 does not. So it expects it in the global scope. All you have to do is go to `globals.js` (or wherever your `global.x` definitions are) and change the definition for `global.crypto` to:

```
global.crypto = require('crypto');
```

**Comment by zhaozhiming** [comment]
@davidperrenoud @flotwig I try both your methods but no work. I use @mattvick 's way is ok.    

```diff
-if ( !crypto ) try { crypto = require('crypto'); } catch (e) {}
+if ( !crypto ) try { crypto = require('crypto-js'); } catch (e) {}
```

**Comment by nivida** [comment]
It looks like this issue is not directly related to web3.js. If it is please write a comment here and I will reopen it.
